[package]
name = "TokenBridgePTBResolver"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
sui_ptb_resolver ={ git = "https://github.com/wormholelabs-xyz/sui-ptb-resolver.git", subdir = "sui_ptb_resolver", rev = "main" }
Wormhole = { git = "https://github.com/wormhole-foundation/wormhole.git", subdir = "sui/wormhole", rev = "sui/mainnet" }
TokenBridge = { git = "https://github.com/wormhole-foundation/wormhole.git", subdir = "sui/token_bridge", rev = "sui/mainnet" }
TokenBridgeRelayerV4 = { git = "https://github.com/wormholelabs-xyz/example-permissionless-token-bridge-executor-shim.git", subdir = "sui/token_bridge_relayer", rev = "sui_tbr_v4" }

[addresses]
token_bridge_ptb_resolver = "0x0"
sui_ptb_resolver = "_"
wormhole = "_"
token_bridge = "_"
token_bridge_relayer = "_"
