[package]
name = "TokenBridgeRelayerV4"
version = "0.4.0"
edition = "2024.beta"

[dependencies]
Wormhole = { git = "https://github.com/wormhole-foundation/wormhole.git", subdir = "sui/wormhole", rev = "sui/mainnet" }
TokenBridge = { git = "https://github.com/wormhole-foundation/wormhole.git", subdir = "sui/token_bridge", rev = "sui/mainnet" }
executor = { git = "https://github.com/wormholelabs-xyz/example-messaging-executor.git", subdir = "sui/executor", rev = "main" }
executor_requests = { git = "https://github.com/wormholelabs-xyz/example-messaging-executor.git", subdir = "sui/executor_requests", rev = "main" }

[addresses]
token_bridge_relayer = "0x0"
wormhole = "_"
token_bridge = "_"
executor = "_"
executor_requests = "_"
